[credentials]

  [credentials.usernames.gmontanari]
  name = "Guilherme Montanari"
  # Cole aqui um HASH (não a senha em texto)
  password = "$2b$12$TROQUE_POR_UM_HASH_GERADO"

[cookie]
name = "mc_auth"
key = "troque-por-uma-chave-bem-grande-e-aleatoria-123456"
expiry_days = 30
