[credentials]

  [credentials.usernames.gmontanari]
  name = "Guilherme Montanari"
  # Cole aqui um HASH (não a senha em texto)
  password = "$2b$12$Ur.YvFnkCBJq6xk4VccgSOH3p1dNjL57QJrtiW6voAAoQwFdfZFNW"
  
[cookie]
name = "mc_auth"
key = "troque-por-uma-chave-bem-grande-e-aleatoria-123456"
expiry_days = 30
